services:

  app:
    build: .
    ports: 
      - "8080:3000"
    env_file:
      - config/local.docker.env
    depends_on:
      - db
    networks:
      - srp

  db:
    image: postgres:16.3
    ports:
      - "32760:5432"
    environment:
      POSTGRES_USER: local_admin
      POSTGRES_PASSWORD: admin_pwd
      POSTGRES_DB: srp
    networks:
      - srp

networks:
  srp:
    driver: bridge